CREATE USER TESISUSR identified by M6aE7heT7 
DEFAULT TABLESPACE ESQUEMATESIS  
QUOTA UNLIMITED ON ESQUEMATESIS  
TEMPORARY TABLESPACE TEMP 
QUOTA 5M ON SYSTEM 
PROFILE TESISPROFILE 
ACCOUNT UNLOCK;
GRANT CREATE SESSION TO TESISUSR;
GRANT CREATE ANY INDEX,
ALTER ANY INDEX,
DROP ANY INDEX TO TESISUSR;
GRANT CREATE SEQUENCE,
CREATE ANY SEQUENCE,
ALTER ANY SEQUENCE,
DROP ANY SEQUENCE,
SELECT ANY SEQUENCE TO TESISUSR;
GRANT CREATE ANY TABLE,
ALTER ANY TABLE,
DELETE ANY TABLE,
DROP ANY TABLE,
INSERT ANY TABLE,
SELECT ANY TABLE,
FLASHBACK ANY TABLE,
UPDATE ANY TABLE TO TESISUSR;
GRANT CREATE ANY VIEW,DROP ANY VIEW,UNDER ANY VIEW TO TESISUSR;
GRANT CREATE ANY PROCEDURE,DROP ANY PROCEDURE,UNDER ANY VIEW TO TESISUSR;
grant create any trigger,drop any trigger to TESISUSR;